### ISSUE TITLE
Load course list from edux

### ISSUE THREAD

**Issue by josefdolezal** [jakub-tucek/fit-checker#1]
Course list can be loaded from Edux through POST request when you are logged in. This url `https://edux.fit.cvut.cz/lib/exe/ajax.php` is called by javascript when you visit edux main page.
Use POST request to retrieve JSON response with list of courses.

There are four _required_ parameters in POST data:
* `call`:  `dashboard_widget_update`
* `lazy`: `1`
* `widget_max`: `0`
* `widget_real_id`: `w_actual_courses_fit`

Sample code in Swft using Alamofire framework:

```swift
let coursesUrl = "https://edux.fit.cvut.cz/lib/exe/ajax.php"
let postParameters = [
    "call": "dashboard_widget_update",
    "lazy": "1",
    "widget_max": "0",
    "widget_real_id": "w_actual_courses_fit"
]

Alamofire.request(.POST, coursesUrl, parameters: postParameters)
    .responseJSON() { response in switch response.result {
        case .Success:
            print(response.result.value)
        case .Failure:
            print("Fail response")
        }        
  }
```

**Comment by jakub-tucek** [comment]
Just implemented it. Works great, thanks a lot!
